### ISSUE TITLE
Relicense under dual MIT/Apache-2.0

### ISSUE THREAD

**Issue by LutzCle** [LutzCle/papi-sys#1]
Hi @alkorang,

Thanks for your contributions! I've merged them into my repository.

However, I'd like to change the license from Apache-2.0-only to a dual MIT/Apache-2.0 license, which is standard in the Rust community. See [the Rust FAQ](https://prev.rust-lang.org/en-US/faq.html#why-a-dual-mit-asl2-license) and https://github.com/sfackler/rust-postgres-macros/issues/19 for an in-depth discussion.

If you don't have any objections, please post your consent with:
```
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.
```

Best,

Clemens

**Comment by yeonsookimdev** [comment]
I have no objection for this relicensing, so **`I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.`**

I never expected that you would merge my commits into yours. Thanks! ;)

**Comment by LutzCle** [comment]
Great, thank you! Then I'll go ahead and perform the relicense.
